logging:
    file:
        name: logs/spring-board.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        root: info

mybatis:
    mapper-locations: classpath:mappers/**/*.xml

server:
    port: 8080
    servlet:
        context-path: /

spring:
    application:
        name: spring-board
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://127.0.0.1:3306/jboard
        username: gudals
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB

    thymeleaf:
        prefix: classpath:/templates

file:
    upload:
        path: uploads/
